export const contracts = [
  {
    ref: "FAR_121",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_122",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_123",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_124",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_125",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_126",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_127",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_128",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_129",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_130",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_131",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_132",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_133",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_134",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_135",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_136",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_137",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_138",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_139",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_140",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_141",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_142",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_143",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_144",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_145",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_146",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_147",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_148",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_149",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
  {
    ref: "FAR_150",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    commodity: "Soya Beans",
    yield: 400,
    offered: 500.0,
    planting_date: "01/04/2023",
    harvest_date: "31/07/2023",
    expected_sale_date: "05/07/2023",
    status: "Active",
    agent: "Mike Mundu",
  },
];

export const agents = [
  {
    id: "1",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "2",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "3",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "4",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "5",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "6",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "7",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "8",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "9",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "10",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "11",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "12",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "13",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "14",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "15",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "16",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "17",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "18",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "19",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "20",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "21",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
  {
    id: "22",
    firstname: "Abdinasir",
    secondname: "Abdullahi",
    phone_number: "Soya Beans",
    total_farmers: 12,
    acreas_registered: "-",
    farmer_traded: "-",
    purchased_volume: "199.00 kgs",
    inventory_volume: "130.00 kgs",
  },
];

export const purchases = [
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },

  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
  {
    purchased_on: "02/06/2023",
    bag_no: "Abdinasir",
    invoice_no: "Abdullahi",
    commodity: "Soya Beans",
    farmer: "Jackson Mwaura",
    agent_name: "Fidelis Gichuhi",
    weight: "123.00",
    price: 245,
    total: 3900,
  },
];
